name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Copy Windows DLLs to package directory
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Copy-Item -Path "C:\Julia\bin\libgomp-1.dll" -Destination "python\chils\libgomp-1.dll"
          Copy-Item -Path "C:\Julia\bin\libwinpthread-1.dll" -Destination "python\chils\libwinpthread-1.dll"
          Copy-Item -Path "C:\Julia\bin\libgcc_s_seh-1.dll" -Destination "python\chils\libgcc_s_seh-1.dll"

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD: cp310-*
          CIBW_ARCHS: ${{(matrix.os == 'ubuntu-latest' && 'auto aarch64' || 'auto') }}
          CIBW_SKIP: "*-musllinux_*"
          CIBW_BEFORE_BUILD_WINDOWS: "pip install delvewheel"
          CIBW_BEFORE_BUILD_MACOS: |
            set -eux
            
            brew install llvm cmake
            
            git clone --depth 1 https://github.com/llvm/llvm-project.git
            cd llvm-project
            
            export MACOSX_DEPLOYMENT_TARGET=11.0
            
            cmake -S runtimes -B build \
              -DCMAKE_BUILD_TYPE=Release \
              -DLLVM_ENABLE_RUNTIMES=openmp \
              -DLIBOMP_ENABLE_SHARED=ON \
              -DLIBOMP_ENABLE_STATIC=OFF \
              -DLIBOMP_INSTALL_ALIASES=OFF \
              -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
              -DCMAKE_INSTALL_PREFIX=$PWD/build/install \
              -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
              
            cmake --build build --parallel

            cmake --install build

            ls -l $PWD/build/install/bin/
            ls -l $PWD/build/install/include/
          CIBW_ENVIRONMENT_MACOS: >
            LIBOMP_ROOT=$PWD/build/install
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: 'delvewheel repair -w {dest_dir} {wheel}'
        with:
          output-dir: wheels

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheels